import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router';
import { animated, Transition } from "react-spring";
import Link from 'next/link'

// store 
import { Provider } from 'react-redux';
import withRedux from 'next-redux-wrapper';

// style 
import '../src/styles/globals.scss'
import styles from '../src/styles/Home.module.scss'
import Store from '../src/store'


function MyApp({ Component, pageProps, store }) {

  const router = useRouter();
  const items = [
    {
      id: router.route,
      Component,
      pageProps,
    },
  ];

  return (
    <Provider store={store}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header className={styles.header} style={{ flexDirection: 'column' }}>
          <h1 className={styles.title} style={{ width: '100%' }}>
            Welcome to <a style={{ display: 'inline-block' }} href="https://nextjs.org">Next.js!</a>
          </h1>

          <ul className={styles.menu}>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/about">About Us</Link>
            </li>
          </ul>
        </header>

        <main className={styles.main}>
          <Transition
            items={items}
            keys={(item) => item.id}
            initial={{ top: 0, opacity: 0 }}
            from={{ top: -20, opacity: 0, position: "relative" }}
            enter={{ top: 0, opacity: 1, position: "relative" }}
            trail={300}
          >
            {(
              styles,
              { pageProps: animatedPageProps, Component: AnimatedComponent },
              key
            ) => (
              <animated.div
                style={{
                  ...styles,
                  width: "100%",
                  height: "100%",
                  overflow: "hidden",
                }}
              >
                <AnimatedComponent {...animatedPageProps} />
              </animated.div>
            )}
          </Transition>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>

      </div>
    </Provider>
  )
}

// const makeStore = () => Store;
// const wrapper = createWrapper(makeStore);

export default withRedux(Store)(MyApp);
